In [2]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt

from datadownloader import DataDownloader
from datasetcreator import columns_to_keep, DataSetCreator

In [3]:
df_test = pd.read_parquet("data-storage/raw_data/7-Ligue 1/27-2015_2016/3829413-2015-08-07-Lille(0)-Paris Saint-Germain(1).parquet")

In [4]:
df_test.columns.tolist()

['ball_receipt_outcome',
 'ball_recovery_offensive',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_offensive',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_no_touch',
 'dribble_nutmeg',
 'dribble_outcome',
 'dribble_overrun',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_lost_in_play',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_end_location',
 'pass_goal_assist',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_no_touch',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_open_goal',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure',
 'blocked',
 'freekick']

In [5]:
df_test['position']

6           Right Center Midfield
7                  Center Forward
1796    Center Defensive Midfield
8       Center Defensive Midfield
1797             Left Center Back
                  ...
932                Center Forward
3005          Left Center Forward
2541          Left Center Forward
3339                         None
3340                         None
Name: position, Length: 1933, dtype: object

In [3]:
df_test = pd.read_parquet("data-storage/xThreat_data_v4_ligue1_1516.parquet", engine='fastparquet')

In [4]:
df_test.head()

,x,y,possession_kept,possession_length,chain_length,previous_deleted,match_id,period,player_id,type,...,under_pressure,position,next_type,next_x,next_y,next_under_pressure,next_team_id,next_player_id,shot,goal
index,,,,,,,,,,,,,,,,,,,,,
8,37.6250,34.085,True,0,0,True,3829413,1,3026.0,Pass,...,NaN,Center Defensive Midfield,Carry,26.0750,28.305,NaN,131.0,3956.0,False,False
1797,26.0750,28.305,True,1,1,False,3829413,1,3956.0,Carry,...,NaN,Left Center Back,Pass,25.6375,30.260,NaN,131.0,3956.0,False,False
9,25.6375,30.260,True,2,2,False,3829413,1,3956.0,Pass,...,NaN,Left Center Back,Carry,24.2375,45.220,NaN,131.0,3295.0,False,False
1798,24.2375,45.220,True,3,3,False,3829413,1,3295.0,Carry,...,NaN,Right Center Back,Pass,27.7375,49.045,NaN,131.0,3295.0,False,False
10,27.7375,49.045,True,4,4,False,3829413,1,3295.0,Pass,...,NaN,Right Center Back,Pass,31.0625,38.080,NaN,131.0,3026.0,False,False

In [8]:
df_test2 = pd.read_parquet("data-storage/xThreat_data_v4_euros2020.parquet", engine='fastparquet')
df_test2.head()

,x,y,possession_kept,possession,possession_length,chain_length,previous_deleted,match_id,id,period,...,shot_statsbomb_xg,pass_height,under_pressure,position,next_type,next_x,next_y,next_under_pressure,next_team_id,next_player_id
index,,,,,,,,,,,,,,,,,,,,,
2088,13.8250,6.375,True,3,0,0,True,3788741,4cbd1088-1580-43f5-8b09-58efabb753ff,1,...,NaN,None,NaN,Left Center Back,Pass,2.8875,10.795,NaN,914.0,6954.0
9,2.8875,10.795,True,3,2,1,False,3788741,bfcfd5ad-1dda-44c9-9f3d-9b33b59983a6,1,...,NaN,Ground Pass,NaN,Left Center Back,Carry,6.9125,30.770,NaN,914.0,7036.0
2089,6.9125,30.770,True,3,3,2,False,3788741,58ef2997-552a-4d3e-854a-cf863f9f5b71,1,...,NaN,None,NaN,Goalkeeper,Pass,7.9625,33.065,NaN,914.0,7036.0
10,7.9625,33.065,True,3,4,3,False,3788741,14604dfa-65b1-40c0-a11e-7c6b037806c0,1,...,NaN,Ground Pass,NaN,Goalkeeper,Carry,17.2375,40.715,NaN,914.0,7173.0
2090,17.2375,40.715,True,3,5,4,False,3788741,5eae5d7a-59cb-42e0-bfc0-c5a2e80493ee,1,...,NaN,None,NaN,Right Center Back,Pass,25.2000,42.415,NaN,914.0,7173.0

In [9]:
df_test3 = pd.read_parquet("data-storage/xThreat_data_v3_euros2020.parquet", engine='fastparquet')
df_test3.head()

,x,y,possession_kept,possession,possession_length,chain_length,previous_deleted,match_id,id,period,...,shot_outcome,shot_statsbomb_xg,pass_height,under_pressure,next_type,next_x,next_y,next_under_pressure,next_team_id,next_player_id
index,,,,,,,,,,,,,,,,,,,,,
2088,13.8250,6.375,True,3,0,0,True,3788741,4cbd1088-1580-43f5-8b09-58efabb753ff,1,...,None,NaN,None,NaN,Pass,2.8875,10.795,NaN,914.0,6954.0
9,2.8875,10.795,True,3,2,1,False,3788741,bfcfd5ad-1dda-44c9-9f3d-9b33b59983a6,1,...,None,NaN,Ground Pass,NaN,Carry,6.9125,30.770,NaN,914.0,7036.0
2089,6.9125,30.770,True,3,3,2,False,3788741,58ef2997-552a-4d3e-854a-cf863f9f5b71,1,...,None,NaN,None,NaN,Pass,7.9625,33.065,NaN,914.0,7036.0
10,7.9625,33.065,True,3,4,3,False,3788741,14604dfa-65b1-40c0-a11e-7c6b037806c0,1,...,None,NaN,Ground Pass,NaN,Carry,17.2375,40.715,NaN,914.0,7173.0
2090,17.2375,40.715,True,3,5,4,False,3788741,5eae5d7a-59cb-42e0-bfc0-c5a2e80493ee,1,...,None,NaN,None,NaN,Pass,25.2000,42.415,NaN,914.0,7173.0

In [10]:
df_test_new = pd.read_parquet("data-storage/xThreat_data_v4.parquet", engine='fastparquet')

In [11]:
df_test_new.head()

,x,y,possession_kept,possession,possession_length,chain_length,previous_deleted,match_id,id,period,...,shot_statsbomb_xg,pass_height,under_pressure,position,next_type,next_x,next_y,next_under_pressure,next_team_id,next_player_id
index,,,,,,,,,,,,,,,,,,,,,
2229,42.875,45.90,True,2,0,0,True,9575,d32867d0-0ad7-457b-84ed-d8d36170a7a8,1,...,NaN,None,NaN,Left Center Midfield,Pass,47.25,51.00,NaN,217.0,5470.0
8,47.250,51.00,True,2,1,1,False,9575,8febae86-5407-4bdf-a22e-afc5838eb9f2,1,...,NaN,Ground Pass,NaN,Left Center Midfield,Carry,50.75,64.60,NaN,217.0,6374.0
2230,50.750,64.60,True,2,2,2,False,9575,471da9a8-b226-4001-99b7-a7315ca838d2,1,...,NaN,None,NaN,Right Back,Pass,49.00,65.45,NaN,217.0,6374.0
9,49.000,65.45,True,2,3,3,False,9575,3993466c-5610-4981-9e88-3e4aeb67a1d2,1,...,NaN,Ground Pass,NaN,Right Back,Carry,33.25,55.25,NaN,217.0,5506.0
2231,33.250,55.25,True,2,4,4,False,9575,bdcc91c2-553b-4ae7-bdb7-7ec61dd92911,1,...,NaN,None,NaN,Right Center Back,Pass,33.25,54.40,NaN,217.0,5506.0

In [13]:
from statsbombpy import sb
competition_id = 7
season_id = 27
# Get the matches for Ligue 1 2015/2016
Ligue_1_season_1516 = sb.matches(competition_id=competition_id, season_id=season_id)

match_list = Ligue_1_season_1516['match_id'].tolist()

c:\Users\kwvanarem\Documents\GitHub\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [15]:
df_test_new_ligue = df_test_new[df_test_new['match_id'].isin(match_list)].copy()

In [16]:
df_test_new_ligue.to_parquet("data-storage/xThreat_data_v4_ligue1_1516.parquet", engine='fastparquet', index=False)

In [17]:
df_test_new_ligue.columns.tolist()

['x',
 'y',
 'possession_kept',
 'possession',
 'possession_length',
 'chain_length',
 'previous_deleted',
 'match_id',
 'id',
 'period',
 'player_id',
 'type',
 'shot_outcome',
 'shot_statsbomb_xg',
 'pass_height',
 'under_pressure',
 'position',
 'next_type',
 'next_x',
 'next_y',
 'next_under_pressure',
 'next_team_id',
 'next_player_id']

In [3]:
import pandas as pd
data_path = 'data-storage/xThreat_data_v4_ligue1_1516.parquet' # version 4 has player position added
df_events = pd.read_parquet(data_path, engine='fastparquet')
df_events['shot'] = ~df_events['shot_outcome'].isna()
df_events['goal'] = df_events['shot_outcome'] == 'Goal'
df_events.drop(columns=['id', 'shot_outcome', 'possession'], inplace=True)
df_size_bytes = df_events.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)  # Convert to MB

print(f"DataFrame size: {df_size_mb:.2f} MB")

DataFrame size: 190.87 MB

In [4]:
df_events.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604704 entries, 0 to 604703
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   x                    604704 non-null  float64
 1   y                    604704 non-null  float64
 2   possession_kept      604704 non-null  bool
 3   possession_length    604704 non-null  int64
 4   chain_length         604704 non-null  int64
 5   previous_deleted     604704 non-null  bool
 6   match_id             604704 non-null  int64
 7   period               604704 non-null  int64
 8   player_id            604704 non-null  float64
 9   type                 604704 non-null  object
 10  shot_statsbomb_xg    4090 non-null    float64
 11  pass_height          317283 non-null  object
 12  under_pressure       162038 non-null  float64
 13  position             604704 non-null  object
 14  next_type            604704 non-null  object
 15  next_x               604704 non-null  float64
 16  next_y               604704 non-null  float64
 17  next_under_pressure  162117 non-null  float64
 18  next_team_id         604704 non-null  float64
 19  next_player_id       604704 non-null  float64
 20  shot                 604704 non-null  bool
 21  goal                 604704 non-null  bool
dtypes: bool(4), float64(10), int64(4), object(4)
memory usage: 190.9 MB